[build]
  publish = "public"
  functions = "functions"

[dev]
  port = 8888
  targetPort = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
